name: todolist_blockchain
description: A new Flutter project with Blockchain

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  web3dart: ^2.3.0
  http: ^0.13.5
  web_socket_channel: ^2.2.0
  hive:
  hive_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator:
  build_runner:

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - src/artifacts/TodoList.json
